services:
  postgres:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-vlm}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vlm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vlm}
      POSTGRES_DB: ${POSTGRES_DB:-vlm}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20


  minio:
    image: minio/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME:-vlm}-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-adminadmin}
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "${MINIO_PORT_API:-9000}:9000"
      - "${MINIO_PORT_CONSOLE:-9001}:9001"
    volumes:
      - minio_data:/data
    # Health is verified externally by scripts/healthcheck.sh using HTTP liveness

volumes:
  postgres_data:
  minio_data:


