name: Infra Check

on:
  pull_request:
    branches: [ master ]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy env example
        run: cp .env.example .env || true

      - name: Start compose
        run: docker compose up -d --wait

      - name: Healthcheck
        run: bash scripts/healthcheck.sh

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present


